### ISSUE TITLE
clipping

### ISSUE THREAD

**Issue by jvcleave** [jvcleave/ofxImGui#1]
some strange clipping going on - doesn't happen with ImGui

![image](https://cloud.githubusercontent.com/assets/150037/9690971/86068448-530d-11e5-9e5f-9cc7625f0e66.png)

**Comment by chuckleplant** [comment]
Hi! Just found imgui and an addon is already on the go :D 
Found this at their Readme:

> I integrated ImGui in my engine and some elements are disappearing when I move windows around..
> 
> Most likely you are mishandling the clipping rectangles in your render function. Rectangles provided by ImGui are defined as (x1,y1,x2,y2) and NOT as (x1,y1,width,height).

That may be the case with oF integration. 
Best!

**Comment by jvcleave** [comment]
interesting - it's been a couple of weeks but I thought it might be related to trying to get glScissor in the OF pipeline. That seems to be the big difference

**Comment by chuckleplant** [comment]
You're most probably right! Just wanted to add that in case it was relevant. ImGUI looks promising!

**Comment by jvcleave** [comment]
yeah - I'm somewhat torn on just going back and using the render stuff from ImGui examples. I thought getting it into OF-speak would make it easier for cross-platform-ness but it might not be worth it

**Comment by jvcleave** [comment]
Seems to be fixed by moving away from ofMesh
