### ISSUE TITLE
input latin characters

### ISSUE THREAD

**Issue by bafonso** [jvcleave/ofxImGui#102]
I'd like to input latin characters such as é ó í ü etc into a text input. I'm using OSX where you use the alt(option) key + e for accent for example. 

Currently I'm doing (addGroup did not work)

`ofxImGui::AddParameter(mainWindow->orquestaName);
`
where orquestaName is a ofParameter<string> variable. 

I sometimes can enter é but most of the times not...

![image](https://user-images.githubusercontent.com/777910/73766103-8e0fc300-4743-11ea-9121-24cd4010d265.png)

**Comment by Daandelange** [comment]
Hey, Good one, same on my side.
However, in the native imgui glfw example it works as expected, so it might be possible in ofxImGui too.
As a workaround, you can use copy and paste. Or use the osx character viewer to insert them.
If characters show as `?`, they are not included in the default imgui font atlas, but that's another issue.

**Comment by Daandelange** [comment]
Fixed in the OpenFrameworks backend too. The ImGui 1.88 I/O implementation has been revamped meanwhile, improving support event further.
