### ISSUE TITLE
ofxImGuiLoggerChannel.h

### ISSUE THREAD

**Issue by cyrstem** [jvcleave/ofxImGui#105]
can someone point out how to use ofxImGuiLoggerChannel.h  or get  the ofLog(); in ofxImGui to work ?

**Comment by Daandelange** [comment]
Hey, good question.
There's [the example]() and another [usecase by sphaero here](https://github.com/hku-ect/MOCAP_CSV2OSC/blob/e1cb57ad9e26caab8d553d4264e38d838f45f654/src/uiWidgets.h).
Also there's [a modification by to capture std output](https://github.com/jvcleave/ofxImGui/pull/90) around.

It looks similar to the imgui logger examples and it feels like there could be some more oF glue. Maybe there's something more oF-native to do involving `ofSetLoggerChannel()`, as it's a `ofBaseLoggerChannel`, like :
https://github.com/d3cod3/Mosaic/blob/60b4a448b53976e80241bf128aff593af8f032e8/src/ofApp.cpp#L73-L74
And there could definitely be an embedded function to render any `ofBaseLoggerChannel` to the gui.

**Comment by cyrstem** [comment]
Hey yup i ended up using this [example ](https://github.com/hku-ect/MOCAP_CSV2OSC/blob/e1cb57ad9e26caab8d553d4264e38d838f45f654/src/uiWidgets.h)
 some time ago  but thanks!
