### ISSUE TITLE
arb textures

### ISSUE THREAD

**Issue by manuliner** [jvcleave/ofxImGui#113]
Hello,

I'm trying to get your example to work but as long as I use your template I only get white rectangles instead of images.

However, if I add ofDisableARBTexture(), images are displayed. 

Do you have any idea how I could use ofxImgui with arbtextures?

greetings

**Comment by Daandelange** [comment]
Hello, Little late to the party.
Related to #101, ImGui only supports 1 type of texture in its renderer. The ofxImGui helpers functions now provide a runtime warning about this : 5bfb1f4.
