### ISSUE TITLE
constexpr float ofColorScale: Syntax error in input

### ISSUE THREAD

**Issue by Jonathhhan** [jvcleave/ofxImGui#125]
The issue appears in the `develop` branch.
I try to make swig bindings and came across this error in `imconfig.h`:
`constexpr float ofColorScale(1.0f/255.0f);`
`..\..\src\..\..\ofxImGui\src\imconfig.h(184) : Error: Syntax error in input(1).`

It works, if I change it to this:
`constexpr float ofColorScale = 1.0f / 255.0f;`

**Comment by Daandelange** [comment]
Thanks for the report, should be fixed now ;)
