### ISSUE TITLE
ImGui :: Image use ofFbo error

### ISSUE THREAD

**Issue by o2co2** [jvcleave/ofxImGui#17]
GLuint id = m_ui.loadTexture(image_fbo.getTexture());
ImGui::Image((ImTextureID)(uintptr_t)id, ImVec2(fingerMovie.getWidth(), fingerMovie.getHeight()));

display blank

**Comment by jvcleave** [comment]
you using the develop branch?

**Comment by o2co2** [comment]
@jvcleave  yes develop branch

**Comment by jvcleave** [comment]
anything but master often a work in progress

You may want to try to use `ofDisableArbTex()` before allocating your FBO. I think that you may be able to give an ofFbo and external texture that you allocate yourself.

The issue is that OF uses ARB textures by default

**Comment by jvcleave** [comment]
Here's how you have to do it

```
    ofFbo::Settings fboSettings;
    fboSettings.width = videoPlayer.getWidth();
    fboSettings.height = videoPlayer.getHeight();
    fboSettings.internalformat = GL_RGBA;
    fboSettings.textureTarget = GL_TEXTURE_2D;
    videoFBO.allocate(fboSettings);
    videoButtonID = videoFBO.getTexture().texData.textureID;
```

**Comment by o2co2** [comment]
Thank you @jvcleave
