### ISSUE TITLE
backspace yields "?" in text fields on Linux

### ISSUE THREAD

**Issue by egradman** [jvcleave/ofxImGui#2]
Running on Ubuntu in a window.  I know you ran into this problem on other platforms!

**Comment by jvcleave** [comment]
might need some logic applied here
https://github.com/jvcleave/ofxImGui/blob/master/src/ofxImGui.cpp#L56

imgui uses `glfwSetCharCallback` in it's example which I thought I was able to get away with as I was capturing the key inputs from OF

https://github.com/ocornut/imgui/blob/master/examples/opengl3_example/imgui_impl_glfw_gl3.cpp#L296
https://github.com/ocornut/imgui/blob/master/examples/opengl3_example/imgui_impl_glfw_gl3.cpp#L151

**Comment by egradman** [comment]
awesome, I’ll take a look.

On Fri, Oct 9, 2015 at 11:03 AM, Jason Van Cleave <notifications@github.com>
wrote:

> might need some logic applied here
> https://github.com/jvcleave/ofxImGui/blob/master/src/ofxImGui.cpp#L56
>
> imgui uses glfwSetCharCallback in it's example which I thought I was able
> to get away with as I was capturing the key inputs from OF
>
>
> https://github.com/ocornut/imgui/blob/master/examples/opengl3_example/imgui_impl_glfw_gl3.cpp#L296
>
> https://github.com/ocornut/imgui/blob/master/examples/opengl3_example/imgui_impl_glfw_gl3.cpp#L151
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jvcleave/ofxImGui/issues/2#issuecomment-146949180>.
>



-- 
*Eric Gradman*
CTO & Mad Inventor
*P:* 213-268-6253 | *W:* twobitcircus.com <http://www.twobitcircus.com/>
*TW:* @egradman <http://www.twitter.com/egradman>

*TWO BIT CIRCUS*
Engineering Entertainment

Inventors | Developers | Performers

**Comment by jvcleave** [comment]
This is pretty old and is working for me. Let me know if still seeing issue
