### ISSUE TITLE
Ubuntu 14.0.4 without programmable pipeline

### ISSUE THREAD

**Issue by Daandelange** [jvcleave/ofxImGui#21]
Hey and thanks for making this OF ImGui wrapper! :D

I noticed a small issue using it on `Ubuntu 14.0.4` : _(in the demo and other apps using `ofxImGui`)_
When I set `FORCE_PROGRAMMABLE` to `0`, the ofApp shows it's normal graphical output, but the UI is completely invisible. Meanwhile the console logs that all shaders compiled correctly.

It could be a false alarm because I'm using the `x.org` `Nouveau` NVidia driver and I'm not able to switch it off as my hardware is broken with the official (proprietary) Nvidia driver.

So is this a bug or is it specifically related to my configuration ? (or rather an ImGui bug?)

Some system information:
 - `[verbose] GL Version:3.3 (Core Profile) Mesa 10.5.9`
 - `uname -r` `3.19.0.43-generic`

**Comment by jvcleave** [comment]
I'm actually getting a segfault on my Linux Machine :/

**Comment by jvcleave** [comment]
Just realized you are talking about the GL Renderer. I am able to run that ok.

**Comment by Daandelange** [comment]
Ok, so without using the `ofGLProgrammableRenderer`, the Gui shows up fine ?

**Comment by jvcleave** [comment]
For me - yes

**Comment by Daandelange** [comment]
Ok, thanks! I'm almost sure this is related to my setup.
I'll post back here if I figure something out.
