### ISSUE TITLE
mouse rightbutton click not working on osx 10.9

### ISSUE THREAD

**Issue by roymacdonald** [jvcleave/ofxImGui#27]
Hey Jason,
Awesome addon! Just played with it for a while an I loved it.
I cant right clic to get contextual menus, edit colors, etc. although it happens to work with the mouse third button. I´m using an Apple mighty mouse. In the mouse status panel in the example it shows that it gets: 
left mouse button as number 0, middle mouse button as number 1 and right mouse button as number 2 which sound fine for me. I'll try to dig deeper in order to get whats going on but maybe you know how to fix this.
All the best!

**Comment by jvcleave** [comment]
It's getting mixed up here:
https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/app/ofAppGLFWWindow.cpp#L954

**Comment by jvcleave** [comment]
https://github.com/openframeworks/openFrameworks/issues/4873

**Comment by roymacdonald** [comment]
Great! thanks.
all the best

**Comment by jvcleave** [comment]
@roymacdonald I wrote this but haven't ran it with a real mouse yet as I am on my laptop.
https://github.com/jvcleave/ofxImGui/tree/fix-glfw-mouse

**Comment by roymacdonald** [comment]
great!. thanks.

**Comment by jvcleave** [comment]
https://github.com/jvcleave/ofxImGui/commit/54e1be7090c48f7ae38b61d46dafae87b13f2861
