### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by martialgallorini** [jvcleave/ofxImGui#3]
Hello,

Not an issue :)

just wanted to say thank you for bringing this addon. This a a great and featurefull Gui

thanks again.

**Comment by jvcleave** [comment]
no problem - I haven't tested/used it a whole lot myself yet so let me know if you have any issues!

**Comment by martialgallorini** [comment]
i will have some tests for a future projet so i will let you informed.
same issues as already opened one though

i will keep in touch
