### ISSUE TITLE
how to use dynamic textures

### ISSUE THREAD

**Issue by carlesgutierrez** [jvcleave/ofxImGui#30]
Hi, 
 Im trying to use this addon to show dynamic images in the GUi. For this Im using the texture inside of an FBO.  Not sure how i should link or bind the texture to resolve this. 
 
 Here is my code. Texture is visible in the Draw app but not inside the GUI. May be some of you know how to do it properly.
Cheers.

```
#include "ofApp.h"

//--------------------------------------------------------------
void ofApp::setup(){
	myFBO.allocate(255, 255);
	myGui.setup();
}

//--------------------------------------------------------------
void ofApp::update(){

	myFBO.begin();
	ofSetColor(255);
	ofRect(0, 0, 255, 255);
	ofSetColor(0);
	ofEllipse(ofVec2f(mouseX, mouseY), 10, 10);
	myFBO.end();

}

//--------------------------------------------------------------
void ofApp::draw(){
	
	ofSetColor(255);

	myFBO.draw(255, 255, 255, 255);

	//required to call this at beginning
	myGui.begin();

	ImGui::Text("Hello");
	ImGui::Image((ImTextureID)(uintptr_t)myFBO.getTexture().getTextureData().textureID, ImVec2(255, 255));

	//required to call this at end
	myGui.end();


}
```

**Comment by jvcleave** [comment]
you have to create the FBO a bit differently - see this

https://github.com/jvcleave/ofxImGui/blob/develop/example-experimental/src/ofApp.cpp#L59

**Comment by carlesgutierrez** [comment]
Thanks that works perfect, and works for any size( Not only powered 2 texture dimensions )

**Comment by armdz** [comment]
Hi! Im having the same problem with dynamics textures, and the link that @jvcleave provides, won't work. 
How its the method to solve that problem ? 
(I tried setting the fbo as TEXTURE_2D, but then that fbo won't work in shaders)

Thanks!
pd: great work! love this gui implementation.

**Comment by jvcleave** [comment]
@armdz 
here is a version of that project's source files

https://gist.github.com/jvcleave/47fc93217a24474abc787dbf5facecb2
