### ISSUE TITLE
Compile errors in QT (windows)

### ISSUE THREAD

**Issue by gorkacortazar** [jvcleave/ofxImGui#31]
I am trying to compile the addon in MSYS2 but I got an strange linker error

`addons/ofxImGui/libs/imgui/src/imgui.cpp:9190: undefined reference to 'ImmGetContext@4'
addons/ofxImGui/libs/imgui/src/imgui.cpp:9196: undefined reference to 'ImmSetCompositionWindow@8'`

Any idea of what could be causing that error? In QT/Linux works like a charm

**Comment by victor-shepardson** [comment]
I'm not using QT (just msys) but the solution was to add -limm32 to PROJECT_LDFLAGS in config.make

**Comment by gorkacortazar** [comment]
That works with MSYS2, in qt that can be configured in the qbs file as: 
`of.linkerFlags: ['-limm32']`

Thanks for the help!
