### ISSUE TITLE
Segmentation fault on glDrawElements (Ubuntu 14.04, NVidia proprietary drivers 352.63)

### ISSUE THREAD

**Issue by memo** [jvcleave/ofxImGui#36]
I haven't used this addon since probably February and March (2016), and something - but I don't know what - has changed since then, as I now get segmentation fault on glDrawElements. See image below.

I'm running Ubuntu 14.04 on Razorblade 14" with Geforce 970M. Any ideas what this might be?
 
![image](https://cloud.githubusercontent.com/assets/144230/15988393/b9922c6c-3003-11e6-9506-1d03b1b974ec.png)

**Comment by jvcleave** [comment]
we had an older bug (mostly with Windows) here
https://github.com/jvcleave/ofxImGui/issues/22

But also this:
https://github.com/jvcleave/ofxImGui/issues/21

Do you get the same error when not using the Programmable Render?

**Comment by memo** [comment]
Ah, good question. I'm not sure, how does one switch from programmable renderer?
btw that reminds me, previously I was on OF 0.9.1, and now I'm on OF 0.9.3. However I just tried on 0.9.1 as well and got the same error.

**Comment by jvcleave** [comment]
you can  change it in main.cpp
https://github.com/jvcleave/ofxImGui/blob/master/example-demo/src/main.cpp

your screenshot looks like an older version of ofxImGui - have you tried the latest release?
https://github.com/jvcleave/ofxImGui/releases/tag/1.49

**Comment by memo** [comment]
doh! I had pulled before I tested, but I didn't realize I had my own fork, and I was just pulling from that :/
I just pulled from upstream and it's working now. Sorry for the bother! (it's late and I'm tired :)

**Comment by jvcleave** [comment]
glad it worked out!
