### ISSUE TITLE
can't understand how to close a window !!!

### ISSUE THREAD

**Issue by StudioDeTelevision** [jvcleave/ofxImGui#40]
Hello,
i spent few hours trying to : 
- hide the debug window
- add a close button in the top corner of a window to let the user close (or hide) it
!!!!
thaaaanks

**Comment by jvcleave** [comment]
```

    static bool showWindow = true;
    
    if(showWindow)
    {
        if(!ImGui::Begin("Pi Mapper", &showWindow))
        {
            ImGui::End();
        }else
        {
            ImGui::Text("Application average %.3f ms/frame (%.1f FPS)",
                        1000.0f / ImGui::GetIO().Framerate,
                        ImGui::GetIO().Framerate);
            ImGui::End();
        }
    }

```

Look in here for other uses:
https://github.com/jvcleave/ofxImGui/blob/master/libs/imgui/src/imgui_demo.cpp

**Comment by StudioDeTelevision** [comment]
thanks Jason
if i put that code between 
 gui.begin();
and gui.end();
it just crash when i click the close button

i guess that ' s not normal , i must have a bad configuration somewhere

have a nice day

**Comment by jvcleave** [comment]
weird - I tested it with example-demo and it was fine

**Comment by StudioDeTelevision** [comment]
in example demo you put it just after gui.begin
or just before gui.end() 
?
thanks

**Comment by jvcleave** [comment]
right after gui.begin();
