### ISSUE TITLE
How can I change the title of "Debug" window?

### ISSUE THREAD

**Issue by Katmai6** [jvcleave/ofxImGui#45]
How can I change the title of "Debug" window?I mean for example I want to make that window's name "App" instead of "Debug", is it possible?

Also, it looks like ofxImGui is the most advanced GUI addon for Openframeworks, thanks for creating it   :)

**Comment by jvcleave** [comment]
```
if(!ImGui::Begin("My Window Name"))
{
   ImGui::End();
 }else
 {
   ImGui::Text("your content here");
   ImGui::End();
}
```
