### ISSUE TITLE
Failed to build example-demo on Raspberry Pi 3 & OF0.9.3/0.9.5

### ISSUE THREAD

**Issue by genleung** [jvcleave/ofxImGui#46]
`
Linking bin/example-demo for linuxarmv6l
g++ -o bin/example-demo  obj/linuxarmv6l/Release/src/ofApp.o obj/linuxarmv6l/Release/src/main.o ../../../addons/obj/linuxarmv6l/Release/ofxImGui/src/EngineGLFW.o ../../../addons/obj/linuxarmv6l/Release/ofxImGui/src/Gui.o ../../../addons/obj/linuxarmv6l/Release/ofxImGui/src/EngineOpenGLES.o ../../../addons/obj/linuxarmv6l/Release/ofxImGui/src/BaseTheme.o ../../../addons/obj/linuxarmv6l/Release/ofxImGui/src/Helpers.o ../../../addons/obj/linuxarmv6l/Release/ofxImGui/src/BaseEngine.o ../../../addons/obj/linuxarmv6l/Release/ofxImGui/libs/imgui/src/imgui_demo.o ../../../addons/obj/linuxarmv6l/Release/ofxImGui/libs/imgui/src/imgui.o ../../../addons/obj/linuxarmv6l/Release/ofxImGui/libs/imgui/src/imgui_draw.o ../../../libs/openFrameworksCompiled/lib/linuxarmv6l/libopenFrameworks.a   -Wl,-rpath=./libs:./bin/libs -Wl,--as-needed -Wl,--gc-sections -pthread -L/opt/vc/lib ../../../libs/kiss/lib/linuxarmv6l/libkiss.a ../../../libs/tess2/lib/linuxarmv6l/libtess2.a  ../../../libs/poco/lib/linuxarmv6l/libPocoNetSSL.a ../../../libs/poco/lib/linuxarmv6l/libPocoNet.a ../../../libs/poco/lib/linuxarmv6l/libPocoCrypto.a ../../../libs/poco/lib/linuxarmv6l/libPocoUtil.a ../../../libs/poco/lib/linuxarmv6l/libPocoJSON.a ../../../libs/poco/lib/linuxarmv6l/libPocoXML.a ../../../libs/poco/lib/linuxarmv6l/libPocoFoundation.a  -L/usr/lib/arm-linux-gnueabihf -lz -lgstapp-1.0 -lgstvideo-1.0 -lgstbase-1.0 -lgstreamer-1.0 -ludev -lfontconfig -lfreetype -lsndfile -lopenal -lssl -lcrypto -lglfw -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lmpg123  -lfreeimage -lboost_filesystem -lboost_system -lXinerama -lrtaudio -lGLESv2 -lGLESv1_CM -lEGL -lopenmaxil -lbcm_host -lvcos -lvchiq_arm -lpcre -lrt -lX11 -ldl
../../../addons/obj/linuxarmv6l/Release/ofxImGui/src/Gui.o: In function `ofxImGui::Gui::setup(ofxImGui::BaseTheme*)':
Gui.cpp:(.text+0x104): undefined reference to `ofxImGui::EngineOpenGLES::setup()'
Gui.cpp:(.text+0x158): undefined reference to `vtable for ofxImGui::EngineOpenGLES'
../../../addons/obj/linuxarmv6l/Release/ofxImGui/src/Gui.o: In function `ofxImGui::Gui::close()':
Gui.cpp:(.text+0x7b0): undefined reference to `ofxImGui::EngineOpenGLES::exit()'
Gui.cpp:(.text+0x860): undefined reference to `vtable for ofxImGui::EngineOpenGLES'
../../../addons/obj/linuxarmv6l/Release/ofxImGui/src/Gui.o: In function `ofxImGui::EngineOpenGLES::~EngineOpenGLES()':
Gui.cpp:(.text._ZN8ofxImGui14EngineOpenGLESD0Ev[_ZN8ofxImGui14EngineOpenGLESD5Ev]+0x20): undefined reference to `ofxImGui::EngineOpenGLES::exit()'
Gui.cpp:(.text._ZN8ofxImGui14EngineOpenGLESD0Ev[_ZN8ofxImGui14EngineOpenGLESD5Ev]+0x38): undefined reference to `vtable for ofxImGui::EngineOpenGLES'
../../../addons/obj/linuxarmv6l/Release/ofxImGui/src/Gui.o: In function `ofxImGui::EngineOpenGLES::~EngineOpenGLES()':
Gui.cpp:(.text._ZN8ofxImGui14EngineOpenGLESD2Ev[_ZN8ofxImGui14EngineOpenGLESD5Ev]+0x20): undefined reference to `ofxImGui::EngineOpenGLES::exit()'
Gui.cpp:(.text._ZN8ofxImGui14EngineOpenGLESD2Ev[_ZN8ofxImGui14EngineOpenGLESD5Ev]+0x30): undefined reference to `vtable for ofxImGui::EngineOpenGLES'
collect2: error: ld returned 1 exit status
../../../libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:382: recipe for target 'bin/example-demo' failed
make[1]: *** [bin/example-demo] Error 1
make[1]: Leaving directory '/home/pi/develop/openframeworks/0.9.5/addons/ofxImGui/example-demo'
../../../libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:125: recipe for target 'Release' failed
make: *** [Release] Error 2
`
It seems that some dependencies , like libraries,  are not met.

**Comment by prisonerjohn** [comment]
I just fixed a couple of issues with the order of includes when using the OpenGL ES engine (https://github.com/jvcleave/ofxImGui/commit/c21928ffb3a6050b3fa5f72ef7162cda2970fbf9). Can you pull from master and try again?

**Comment by jvcleave** [comment]
seems to work!
