### ISSUE TITLE
Compilation error in project using ofxCv on Windows

### ISSUE THREAD

**Issue by mruegenberg** [jvcleave/ofxImGui#48]
In a project that also includes [ofxCv](https://github.com/kylemcdonald/ofxCv), I get the following compilation error:

~~~~
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(936,5): warning MSB8027: Two or more files with the name of Helpers.cpp will produce outputs to the same location. This can lead to an incorrect build result.  The files involved are ..\..\..\addons\ofxCv\libs\ofxCv\src\Helpers.cpp, ..\..\..\addons\ofxImGui\src\Helpers.cpp.
~~~~

I guess the error is pretty self-explanatory. MSVC can't handle the same filename existing twice in the same project and I indeed get a linker error later on.

The solution would be for either ofxCv or ofxImGui or both to rename Helpers.cpp/.h

See also the corresponding [ofxCv issue](https://github.com/kylemcdonald/ofxCv/issues/205).

**Comment by mruegenberg** [comment]
Closing this since it seems like this was an isolated incident and never occured again. Hopefully will help someone when googling with a similar issue.

**Comment by jeffcrouse** [comment]
I just got this issue. @mruegenberg did you do something (besides renaming the file) to fix it?
