### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by hluisi** [jvcleave/ofxImGui#5]
I'm trying to get images to work but no matter what I do, I only see the font texture.  My guess is that it has something to do with the fontTexture.bind() in ofxImGui::renderDrawLists().  Any suggestions? 

Thnaks :)

**Comment by jvcleave** [comment]
Try the latest master - there also an example in the example-demo

**Comment by hluisi** [comment]
Working now, thanks!

Also it's about 100x faster now. :)
