### ISSUE TITLE
ofParameter save special character

### ISSUE THREAD

**Issue by Wolftronics-SBC** [jvcleave/ofxImGui#69]
if ## is in the name not save to xml
     `  ofParameter<int> min{ "##Min", 5000, 5000, 65535 }; // not save ## ?
	ofParameter<int> max{ "Max", 5000, 5000, 65535 };
	ofParameterGroup parameters{ "Parameters", min, max };`

	ofXml xml;
	ofSerialize(xml, parameters);
	xml.save("settings.xml");

**Comment by jvcleave** [comment]
does the code work without ofxImGui? Sounds like an issue with ofXml or ofSerialize

**Comment by Wolftronics-SBC** [comment]
code not work without ofxImGui.

**Comment by Wolftronics-SBC** [comment]
not save min max value  only position save

**Comment by Wolftronics-SBC** [comment]
ofXml child	= xml.findFirst(name);   I think this is a problem.

**Comment by Wolftronics-SBC** [comment]
`	ofXml child	= xml.findFirst(name);

	if(!child || !name.find("##")){`

**Comment by jvcleave** [comment]
closing since the code doesn’t work without ofxImGui.
