### ISSUE TITLE
ui does not show up on Android device

### ISSUE THREAD

**Issue by brucelane** [jvcleave/ofxImGui#7]
hi,
I used the android release repo of openFrameworks, added ofxImGui to addons.make, added mUi setup,etc from your readme.md file, it compiles and runs fine, but the UI does not not show up.
my repo: https://github.com/brucelane/Reymenta-Mobile/tree/openFrameworks
thank you for any hint
Bruce

**Comment by jvcleave** [comment]
I don't have an Android Device to test :/

I am assuming Android uses Open GL ES 2? Have you tried the release version/example-demo?

**Comment by brucelane** [comment]
Here are the results with my tests on the Android device with example-demo:
- settings.setGLESVersion(2) makes the app quit just after launch
- glWindowSettings.setGLVersion(3, 2) is ok, I used it
- ImGui::GetIO().Framerate returns 60
But no better

**Comment by jvcleave** [comment]
The 60 may be locked to ofSetVerticalSync(true) which is OF's default

**Comment by brucelane** [comment]
framerate is ok.
But "no better" means the UI doesn't display on the screen

**Comment by jvcleave** [comment]
just pushed a bunch of ES changes into master - it's messy still but worth a try to see if it helps

**Comment by brucelane** [comment]
yes it works!!!
thank you so much
![screenshot_2015-12-14-11-47-11](https://cloud.githubusercontent.com/assets/138158/11778998/b225eb28-a258-11e5-87d7-8c8986413bb7.png)

**Comment by jvcleave** [comment]
Nice :)
