### ISSUE TITLE
EXC_BAD_ACCESS when closing app in iOS

### ISSUE THREAD

**Issue by ukelady** [jvcleave/ofxImGui#74]
Hi! For some reason my app is crashing when closing the app on an iPad.

It first crashes in `ImGui::Shutdown(`) inside `SaveSettings()`. 
<img width="1231" alt="screen shot 2018-04-20 at 12 14 12" src="https://user-images.githubusercontent.com/1383198/39046811-c735a93e-4497-11e8-9f30-d3717802352e.png">

Since I don't care about saving settings I comment out SaveSettings() and then it crashes in the following for loop:
```cpp
for (int i = 0; i < g.Windows.Size; i++)
    {
        g.Windows[i]->~ImGuiWindow(); // <-- crash here
        ImGui::MemFree(g.Windows[i]);
    }
...
ImGuiWindow::~ImGuiWindow()
{
    DrawList->~ImDrawList(); // <-- crash here
    ImGui::MemFree(DrawList);
    DrawList = NULL;
    ImGui::MemFree(Name);
    Name = NULL;
}
```
<img width="1201" alt="screen shot 2018-04-20 at 12 25 21" src="https://user-images.githubusercontent.com/1383198/39046817-d04ad896-4497-11e8-95aa-00e77c4ba540.png">

Shutdown is called automatically before `exit` callbacks because it's in some kind of "release pool".
<img width="1211" alt="screen shot 2018-04-20 at 12 39 13" src="https://user-images.githubusercontent.com/1383198/39046836-e3112890-4497-11e8-9787-ae03f15f4226.png">

Do you have any ideas for debugging this? The same program was working fine last year, but I don't know if an update to OF (now 0.10), to my program or to iOS is causing this. ofxImGui has not been changed in my system.

**Comment by jvcleave** [comment]
I would try

if(DrawList)
{
  DrawList->~ImDrawList();
  ImGui::Memfree(Drawlist);
}

**Comment by ukelady** [comment]
Thanks for the suggestion! It turns out that our imgui object is not explicitly deleted during destruction phase. Now it's working fine :)
