### ISSUE TITLE
imconfig.h support for glm::vec2 glm::vec4 etc.

### ISSUE THREAD

**Issue by ocornut** [jvcleave/ofxImGui#77]
Hello,

Since OF appear to be moving to glm::vec2, perhaps the imconfig.h files provided in this project should support both glm::vec2 and ofVec2 for implicit cast with ImVec2? Likely for color and ImVec4 etc.

I'm on a OF user myself but heard of some user who had trouble with the different types and didn't realized than imconfig.h is meant to facilitate exactly this. 

Thanks!

**Comment by ocornut** [comment]
My apologies, this was a mistake since it appears that this is already very well supported:
https://github.com/jvcleave/ofxImGui/blob/master/src/imconfig.h

So it is mostly a discovery/documentation issue that some users don't realize this. Perhaps the README.md could add a paragraph to mention that users can use glm::vec2 or ofVec2 instead of ImVec2?

Thanks for sorry for posting a wrong issue..

**Comment by hamoid** [comment]
Since glm is now the default, maybe the examples can be updated to use that, right?
