### ISSUE TITLE
it's possible to use more than one instance of ofxImGui (inside classes) in the same ofApp?

### ISSUE THREAD

**Issue by moebiussurfing** [jvcleave/ofxImGui#93]
I have an ofApp with some classes.
One class have an ofxImGui working fine.

But when adding another class with another ofxImGu both panels are like locked, no mouse interaction.

The window settings are like shared by both instances or something...

Whats a good way to use more than one classes with ofxImGui's?

**Comment by moebiussurfing** [comment]
sorry, I see this pull request with this:
https://github.com/jvcleave/ofxImGui/pull/53

**Comment by moebiussurfing** [comment]
solved using this branch:
https://github.com/jvcleave/ofxImGui/pull/91

**Comment by Daandelange** [comment]
This should be fully supported now (in the develop branch), closing this ;)

For the record, two types of context sharing have been setup :
1. Seamlessly share ofxImGui instances and `setup()` (for use by multiple plugins).
2. Singleton : one ImGui context instance per ofAppBaseWindow until ImGui supports secondary host viewports. Context are isolated from each other.
